spring.application.name=analyzer-auth-server

# postgres database
spring.datasource.url=jdbc:postgresql://localhost:5432/analyzer_db
spring.datasource.username=db-username
spring.datasource.password=db-password
spring.datasource.driver-class-name=org.postgresql.Driver

#This specific setting makes hibernate update the schema automatically when making @Entity classes or such. 
#It's okay for the start of development, but when database schemas stabilize and application gets deployed, this should be changed to Flyway or something
#so that schema changes are versioned, reviewable, etc. Then we don't just rely on hibernate to infer everything. 
#Consider switching to flyway sooner rather than later, since it is more painful to do when you have a lot of schemas...
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect